site_name: Agents in Action
theme:
  name: material
nav:
  - Introduction: index.md
  - Chapter 01 - From LLMs to AI Agents: from-llms-to-ai-agents.md
  - Chapter 02 - Agents are Here and They are Staying: agents-are-here-and-they-are-staying.md
  - Chapter 03 - n8n - Build Your First Agent Workflow:
    - n8n - Your No-Code Platform for Building AI Agents: meet-n8n.md
    - Hello n8n - Your First Agent Workflow: 101-hello-n8n.md
    - Webhook - The Superpower that Connects Your Backend and Frontend: 201-basic-webhook.md
    - Connect n8n to Lovable using Webhooks: 301-lovable-webhook-n8n.md
    - Your All in One Lovable for Any Workflow: 401-all-in-one-lovable.md
    - Chat with Your Agents using Webhooks: 411-agents-chat-frontend.md
  - Chapter 04 - Sales Agent to Find the Right Customer: sales-agent-to-find-the-right-customer.md
  - Chapter 05 - Build a RAG Agent with Webhook: 301-webhook-rag.md
  - Chapter 06 - Connecting Your Agent with RAG and Internet Search: 401-webhook-rag-with-internet-search.md
  - Chapter 07 - Connecting Your RAG Agent with Memory: supabase-rag-with-memory.md
  - Chapter 08 - Voice RAG Agent: book-companion-voice-rag-agent.md
  - Chapter 09 - Automate Your Content - YouTube to LinkedIn Agent: youtube-to-linkedin-agent.md
  - Chapter 10 - The Unofficial AirBnb AI Agent: the-unofficial-airbnb-ai-agent.md
  - Chapter 11 - LinkedIn Human in the Loop Agent: linkedin-post-human-in-the-loop.md
  - Chapter 12 - The Ultimate AI Blog Post Agent: the-ultimate-ai-blog-post-agent.md
  - Chapter 13 - Fully Functional Agent Loop - Travel-Agent: travel-agent.md
  - Chapter 14 - Intelligent Research - The Ultimate AI Research Assistant: the-ultimate-ai-research-assistant.md
  - Chapter 15 - Investment Intelligence - The Ultimate AI Finance Agent: the-ultimate-ai-finance-agent.md
  - Chapter 16 - Agent that Creates Other Agents: workflow-creator.md
