site_name: Agents in Action
theme:
  name: material
nav:
  - Home: index.md
  - Chapter 01 - What are Agents?:
    - Agents are Here and They are Staying: 1a-agents-are-here-and-they-are-staying.md
    - From LLMs to AI Agents: 1b-from-llms-to-ai-agents.md
  - Chapter 02 - Problem-Centric Approach:
    - Solve a Real World Problem: 2a-solve-a-real-world-problem.md
    - Lovable - From Idea to Prototype: 2b-lovable-from-idea-to-prototype.md
  - Chapter 03 - Prompt vs Context Engineering:
    - Writing Effective Prompts: 3a-writing-effective-prompts.md
    - Understanding Context Engineering: 3b-understanding-context-engineering.md
  - Chapter 04 - Building No-Code Workflows:
    - Agents vs Workflows: 4a-agents-vs-workflows.md 
    - n8n - Getting Started: 4b-n8n-getting-started.md
    - Build Your First Sales Agent: 4c-build-your-first-sales-agent.md
  - Chapter 05 - How Agents Think?: 
    - How Agents Think - Agentic Design Patterns: 5a-how-agents-think.md
  - Chapter 06 - Full Stack Agents:
    - Webhook - Connecting the Dots: 6a-basic-webhook.md
    - Developing Full Stack Agents: 6b-developing-full-stack-agents.md
  - Chapter 07 - Memory:
    - Memory - The Agent's Brain: 7a-memory-the-agents-brain.md
  - Chapter 08 - Agentic RAG:
    - Agentic RAG Ecosystem: 8a-agentic-rag-ecosystem.md
    - n8n - RAG: 8b-webhook-rag.md
    - RAG with Internet Search: 8c-webhook-rag-with-internet-search.md
    - RAG with Memory: 8d-supabase-rag-with-memory.md
    - Voice RAG Agent: 8e-book-companion-voice-rag-agent.md
  - Chapter 09 - Content Automation:
    - YouTube to LinkedIn Agent: 9a-youtube-to-linkedin-agent.md
    - LinkedIn Human in the Loop Agent: 9b-linkedin-post-human-in-the-loop.md
    - Blog Post Agent: 9c-the-ultimate-ai-blog-post-agent.md
  - Chapter 10 - Multimodal Agents: 
    - Multimodal Agents: 10a-multimodal-agents.md
  - Chapter 11 - Scaling Agents:
    - Architectures with Google ADk, A2A, and MCP: 11a-architectures-with-google-adk-a2a-and-mcp.md
  - Chapter 12 - Fully Functional Agent Loop:
    - Travel Agent: 12a-travel-agent.md
  - Chapter 13 - Intelligent Research:
    - Dual Search - The Ultimate AI Research Assistant: 13a-the-ultimate-ai-research-assistant.md
  - Chapter 14 - Inverstment Intelligence:
    - The Ultimate AI Finance Agent: 14a-the ultimate-ai-finance-agent.md
  - Chapter 15 - Workflow Automation:
    - Workflow Creator Agent: 15a-workflow-creator.md 
