site_name: Agents in Action
theme:
  name: material
nav:
  - Home: index.md
  - Blogs:
    - agents-are-here-and-they-are-staying: 01-agents-are-here-and-they-are-staying.md
    - how-agents-think: 02-how-agents-think.md
